#introduction

In [ ]:
print("Hello")

Hello


In [ ]:
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [ ]:
a=50
b=50
c=a+b
print(c)

100


In [ ]:
l = [1,2,3,4,5,6]
for i in l:
  print(i)


1
2
3
4
5
6


In [ ]:
len(l)

6

In [ ]:
l

[1, 2, 3, 4, 5, 6]

In [ ]:
l=(8,9,10)

In [ ]:
l1=[1,1,1,2,2,2,3,3,3,4,4]
s=set(l1)
print(s)


{1, 2, 3, 4}


In [ ]:
l1[::-1]

[4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1]

In [ ]:
l1[-1]

4

In [ ]:
s1=input("Enter the name")
s = "mom"

def isPalindrome(s):
  return s == s[::-1]

ans = isPalindrome(s)

if ans:
  print("Yes")
else:
  print("No")

Enter the name mom
Yes


In [ ]:
import random
num=[1,2,3,4,5,6,7,8]
random.shuffle(num)
print(num)

[1, 5, 4, 8, 7, 3, 2, 6]


In [ ]:
days=['Monday','Tuesday','Wednesday','Thursday','Friday']
'wedneday' in days

False

In [ ]:
list=["red","green","blue"]
print(list)
list.clear()
print(list)

['red', 'green', 'blue']
[]


In [ ]:
nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)

[1, 2, 3, 4, 1, 4, 1, 7, 8, 1]


4

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
a=['a','b','c']
print(a)
a.append('d')
print(a)

['a', 'b', 'c']
['a', 'b', 'c', 'd']


In [ ]:
list=['red','green','blue','yellow']
print(list)
list.clear()
print(list)

['red', 'green', 'blue', 'yellow']
[]


In [ ]:
nums=[1,2,3,4,1,4,1,7,8,1]
print(nums)
nums.count(1)


[1, 2, 3, 4, 1, 4, 1, 7, 8, 1]


4

In [ ]:
list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [ ]:
A=[1,2,3,4]
B=[5,6,7,8]
A.extend(B)
print(A)
print(B)

[1, 2, 3, 4, 5, 6, 7, 8]
[5, 6, 7, 8]


In [ ]:
a=(5)
print(a)
type(a)

5


int

In [ ]:
b=(6.5,9.4)
print(b)
type(b)

(6.5, 9.4)


tuple

In [ ]:
mix=("hello",708,66.8,1,2)
mix

('hello', 708, 66.8, 1, 2)

In [ ]:
set={1,2,3,4,5,6,7,8,9}
set

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
def add():
  a=5
  b=5
  sum=a+b
  print(sum)
add()

10


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
a.size

4

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.size

9

In [ ]:
a.shape

(3, 3)

In [ ]:
z1=np.zeros(3)
print(z1)

[0. 0. 0.]


In [ ]:
array=([[[0.,0.,0.,0.,],
       [0.,0.,0.,0.,],
       [0.,0.,0.,0.,]],

       [[0.,0.,0.,0.,],
        [0.,0.,0.,0.,],
        [0.,0.,0.,0.,]]])
print(array)

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]], [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]


In [ ]:
a1=np.ones(3)
print(a1)

[1. 1. 1.]


In [ ]:
array=([[[1.,1.,1.,1.,],
       [1.,1.,1.,1.,],
       [1.,1.,1.,1.,]],
       [[1.,1.,1.,1.,],
        [1.,1.,1.,1.,],
        [1.,1.,1.,1.,]]])
print(array)

[[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]], [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]]


In [ ]:
array=([[['1','1'.,1.,1.,],
       [1.,1.,1.,1.,],
       [1.,1.,1.,1.,]],
       [[1.,1.,1.,1.,],
        [1.,1.,1.,1.,],
        [1.,1.,1.,1.,]]])
print(array)